spring:
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      #      org.hibernate.envers.track_entities_changed_in_revision: true
      hibernate:
        format_sql: true
        use_sql_comments : true
        enable_lazy_load_no_trans : true
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root